# Generated by Django 5.0.7 on 2024-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wailistentry',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
